name: Docker CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    build-test-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3.5.3
            
            - name: Login to Docker Hub
              uses: docker/login-action@v2.2.0
              with:
                  username: ${{ secrets.DOCK_UNAME }}
                  password: ${{ secrets.DOCK_PAT }}


            - name: Build and Push Docker Image
              uses: docker/build-push-action@v4.1.1
              with:
                  context: .
                  push: true
                  tags: sivepanda/soundbitsserver:${{ github.sha }}

            - name: Deploy to EC2 Instance
              uses: appleboy/ssh-action@master
              env:
                HOSTNM: ${{secrets.HOSTNM}}
                AWS_USR: ${{secrets.AWS_USR}}
                PASS: ${{secrets.PASS}}
                AWS_DB: ${{secrets.AWS_DB}}
              with:
                host: ${{ secrets.AZN_HST }}
                username: ${{ secrets.AZN_AK }}
                key: ${{ secrets.AZN_SAK }}
                script: |
                  sudo service docker start
                  docker stop soundbitsserver || true
                  docker rm soundbitsserver || true
                  docker pull ${{ secrets.DOCK_UNAME }}/soundbitsserver:${{ github.sha }}
                  docker run -d --name soundbitsserver -p 3000:3000 --env-file .env ${{ secrets.DOCK_UNAME }}/soundbitsserver:${{ github.sha }}




